- generic [ref=e2]:
  - heading "🏭 T-Shirt Factory" [level=1] [ref=e3]
  - paragraph [ref=e4]: Multi-Agent Simulation with Live Animation
  - generic [ref=e5]:
    - generic [ref=e6]:
      - generic [ref=e7]: Number of Orders
      - spinbutton "Number of Orders" [ref=e8]: "10"
    - generic [ref=e9]:
      - generic [ref=e10]: Urgent Ratio
      - spinbutton "Urgent Ratio" [ref=e11]: "0.3"
    - button "▶ Start Simulation" [ref=e12] [cursor=pointer]
  - link "📋 View Past Runs" [ref=e14] [cursor=pointer]:
    - /url: /history